trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'flaskdemo'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
    displayName: 'Use Python 3'

  - script: pip install -r requirements.txt
    displayName: 'Install dependencies'

  - task: Docker@2
    inputs:
      containerRegistry: 'acr-flaskdemo'
      repository: 'flaskdemo'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: '$(Build.BuildId)'
    displayName: 'Build and Push Docker image'
